spring.application.name=gestao_partidas_beach_tenis

spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_partidas_beach_tenis
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

# security.token.secret=JAVAGAS_@123#
# security.token.secret.candidate=JAVAGAS_@123#CANDIDATE
security.token.secret.admin=GESTAO_PARTIDAS_BEACH_TENIS_@123#ADMIN

# Configuração de upload de arquivos
file.upload-dir=uploads/avatars
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
